#ifndef CYG_FINCLIENTCOMPONENT_GLOBAL_H
#define CYG_FINCLIENTCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CYG_FINCLIENTCOMPONENT_LIBRARY)
#define CYG_FINCLIENTCOMPONENT_EXPORT Q_DECL_EXPORT
#else
#define CYG_FINCLIENTCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // CYG_FINCLIENTCOMPONENT_GLOBAL_H 