#ifndef CYG_AICLIENTCOMPONENT_GLOBAL_H
#define CYG_AICLIENTCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CYG_AICLIENTCOMPONENT_LIBRARY)
#define CYG_AICLIENTCOMPONENT_EXPORT Q_DECL_EXPORT
#else
#define CYG_AICLIENTCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // CYG_AICLIENTCOMPONENT_GLOBAL_H 