#ifndef CYG_CLIENTEXAMPLE_GLOBAL_H
#define CYG_CLIENTEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CYG_CLIENTEXAMPLE_LIBRARY)
#define CYG_CLIENTEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define CYG_CLIENTEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CYG_CLIENTEXAMPLE_GLOBAL_H
